### PR TITLE
[JOSS] Draft paper and add PDF generation gh-action

### PR DESCRIPTION
**Pull request by mscheltienne**

### CODE REVIEW

**Comment by mscheltienne** [comment]
This PR adds the workflow, draft and bibliography for a short JOSS paper for `mne-lsl`. I believe the version 1.5 with the addition of the `EpochsStream` object and with the additional examples and tutorials is in a sufficiently advance state. It is now fully replacing and improving all features from `mne-realtime`.

@larsoner @dnastars @dbdq You are all co-authors on the publication, @larsoner for all the help debugigng, testing, and improving the infrastructure; @dnastars @dbdq for your contribution to NeuroDecode which served as foundation to this project (for instance, the original viewer is still mostly present).

Please let me know if you agree to be co-author on this paper. Feel free to review the draft, feedback is welcome :smile:

**Comment by larsoner** [comment]
Happy to co-author!

**Comment by dbdq** [comment]
Good for me. Let me know when you want me to review!

**Comment by mscheltienne** [comment]
@dbdq Ready for review on my end, I'd love to hear your feedback when able 😄

**Comment by dnastars** [comment]
Hi Mathieu! Thank you for reaching out! I am also ok!

Best,
Arnaud

**Pull request merged**
